version: "3"

services:

  health-service:
    container_name: "health_service"
    build: .
    ports:
      - "8080:8080"
    networks:
      - health-net

  sonarqube:
    image: sonarqube:lts-community
    container_name: 'health_sonar'
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - health-net

networks:
  health-net: